import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { SessionProvider } from "next-auth/react"
import Head from 'next/head'

function MyApp({ Component, pageProps:{session, ...pageProps} }: AppProps) {
  return (
    <SessionProvider session={session}>
        <Head>
          <title>Happy Routine</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://unpkg.com/flowbite@1.4.7/dist/flowbite.min.css" />
          <script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js"></script>
        </Head>
      <Component {...pageProps} />
    </SessionProvider>
  )
}

export default MyApp
