
name: prisma
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: app

    steps:
      - name: Run prisma client generate
        run: |
            npx prisma generate
