
name: prisma
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Run prisma client generate
        run: |
          echo $GITHUB_WORKSPACE
          npx prisma generate
