
name: prisma
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run prisma client generate
        working-directory: ./app
        run: |
              npx prisma generate
