
name: prisma
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
      - name: Run prisma client generate
        run: |
              npx prisma generate
